### ISSUE TITLE
Allow middleware package to parse tokens and set userId

### ISSUE THREAD

**Issue by aldeed** [stubailo/meteor-rest#23]
Here is my suggestion for how to refactor auth token checking and method/pub userId:

#### Step 1

Create a package that attaches middleware to `JsonRoutes.middleWare`. The middleware will parse the auth token (or any other type of auth) if it should, and set `req.userId`.

```js
JsonRoutes.middleWare.use(function (req, res, next) {
  var userId = getUserIdFromRequest(req);
  if (userId) {
    req.userId = userId;
  }
  next();
});
```

For example, pkg name might be `meteor-accounts-token-middleware`.

#### Step 2

The rest-accounts-password package (and any future FB, etc.) can depend on this package. It is better to have the related rest login pkg depend on it than to have simple:rest depend on it.

#### Step 3

In simple:rest, remove the `getUserIdFromRequest` code and instead do `var userId = req.userId || null`.

#### Net Effect

If you use rest-accounts-password to log in and then supply token to method/pub calls, `this.userId` will be set correctly. That is no change from now, BUT it allows me and others to very easily drop in our own auth middleware that will set `userId` based on a different login/token scenario.

**Comment by aldeed** [comment]
@stubailo I'm happy to do a PR for this if you agree.

**Comment by jperl** [comment]
:+1:

**Comment by stubailo** [comment]
So this is better because it lets you change auth logic without passing a `getUserIdFromRequest` function everywhere? How is it different from a configuration option? So that other packages could share auth code?

**Comment by aldeed** [comment]
I also considered allowing `getUserIdFromRequest` option for methods/pubs. If we do like you suggested and allow the routes to inherit from a single route definition, that could work. But this seemed like an easier way to allow the auth/login package itself to set up the token checking automatically. Plus multiple middleware packages could be added to support checking auth against multiple ways of authenticating.

**Comment by stubailo** [comment]
Yeah, I guess this is also how login handlers work in Meteor (there is one method called `login` which calls all of the handlers in order) so maybe the middleware approach is more correct.

I like this idea, if we do it right it will be a big improvement. I'd also love to work with @kahmali to unify this with what Restivus does.

**Comment by aldeed** [comment]
Also this might be generic enough that different rest packages could all work with the auth packages. Like restivus could also be updated to check for req.userId and then a single package could authenticate users for various swappable rest packages. I don't know how likely that is.

**Comment by stubailo** [comment]
Yeah I think that would be awesome to have in core to solve HTTP authentication once and for all.

**Comment by kahmali** [comment]
I've been thinking about it recently, and my goal is to slowly transition away from Restivus and toward a modular set of packages built to integrate with simple:rest (e.g., simple-roles, simple-collections, simple-json-patch, etc). I can't think of any reason why someone would need to separate their DDP and REST APIs (if anyone can, I'm certainly open to debate). Of course, I will continue to support Restivus until all the existing functionality is supported in simple:rest. 

This way, simple:rest can serve as the foundation for any REST API in Meteor, and then users can modularly add functionality with middleware packages and additional wrappers around simple:rest (for things like collections support maybe). I think setting simple:rest up so that the middleware is pluggable is an ideal solution. My only thought is that the order of the middleware stack needs to be cleanly controlled. For instance, if I want to add a layer of middleware that authenticates a user's role, I need to be sure that its run after any auth middleware (and before the user-defined endpoint is executed). Or if I want to add middleware for converting all responses to a standard format, I would want to be sure that it was inserted after the endpoint was executed, but before the response was returned. I'm not sure of the best way to do this yet. 

Iron Router appears to allow the order of the middleware stack to be controlled, so we might be able to borrow some ideas from them: https://github.com/iron-meteor/iron-middleware-stack/blob/master/lib/middleware_stack.js#L93. I also like what they do with the shared context between middleware. 

My initial motivation behind this was allowing Restivus users to hook into certain parts of the endpoint lifecycle. Here's a [little more info on that](https://github.com/kahmali/meteor-restivus/issues/57), including a list of significant entry points into the lifecycle (a lot have been requested by users).

I'll try to give this some more thought asap, but moving towards pluggable middleware would only make things easier for Restivus, and REST APIs in Meteor in general.

**Comment by stubailo** [comment]
@aldeed @kahmali what would be the best way for us to work together on this? On the one hand, I'd like to remove the friction of you guys having to submit PRs all of the time and having me manually merge them, on the other hand we should still communicate and make sure that we agree on stuff before adding code to these packages.

Maybe I should add you as maintainers, but we can still agree to do code reviews/design discussions before merging stuff in? Should we track this stuff in GitHub or on Trello, for example? Or in a Slack channel somewhere (are you guys on the Meteor Club, Telescope, or SpaceTalk Slack teams?)

**Comment by aldeed** [comment]
SGTM, but even if we're maintainers I'd still want to do PRs from branches and get review. I think @jperl is going to set up a same-room slack channel for our discussions if that works for you.

**Comment by kahmali** [comment]
@stubailo I'm definitely up for that. I agree with @aldeed on the workflow.

**Comment by jperl** [comment]
Sent @stubailo an email w/ the sameroom link

**Comment by stubailo** [comment]
I'm in the channel!

**Comment by stubailo** [comment]
Going back to the original topic, I like this design! Also, I think we should do more of posting the design first and then implementing, then we can all agree on the ideas without having to wade through code.
