### ISSUE TITLE
Figure out release schedule

### ISSUE THREAD

**Issue by stubailo** [stubailo/meteor-rest#37]
Should we release new versions for every change, or try to batch them somehow?

**Comment by aldeed** [comment]
We can decide on this once 0.3.0 is out.

**Comment by kahmali** [comment]
One thing I think we should do is tag our releases. We should use signed, annotated tags. I'm not 100% sure about the naming convention since we have to identify versions for different packages:
```bash
git tag -s json-routes-v0.3.0 -m "JSON Routes - Version 0.3.0"
```

This makes it a lot easier to diff between versions (without having to search through commit messages and hashes): https://github.com/aldeed/meteor-autoform/compare/v5.2.0...v5.3.0

Once we do this we can add these diffs to the change logs.

**Comment by aldeed** [comment]
:+1:

**Comment by stubailo** [comment]
I think the best thing to do would be to automate this with a script that simultaneously updates the version number of the package in `package.js`, publishes the package, and pushes the git tag. So something like:

```sh
./publish-version json-routes 0.3.0
```

**Comment by kahmali** [comment]
I like that @stubailo. Anything to make life a little easier for all of us. We'll just need to consider the possibility of bumping multiple versions in a single commit (unless we just always want to keep them separate. The commit messages and tags could all still work while bumping multiple package versions in a single commit. Sounds like a neat script to release for other meteor devs too (maybe in a separate repo or at least a gist). I would certainly use it with any other packages I develop.

**Comment by stubailo** [comment]
@kahmali I think the script should still work in the case of multiple package releases from one commit. It wouldn't actually create a new commit, just tag the most recent one.
