### ISSUE TITLE
json-routes unblock

### ISSUE THREAD

**Issue by navinSing** [stubailo/meteor-rest#84]
how does unblock() works .. 
called this.unblock() raised an exception .. is it part of the same fiber.. how can subsequent clients make 
request if the processing of the request  is taking long time to execute or makes an external call(which may need unblock). 

Ref : http://docs.meteor.com/#/full/method_unblock

**Comment by stubailo** [comment]
You don't need unblock here. Each server side route runs asynchronously by default.

Meteor methods use unblock because by default meteor intentionally only runs one method per client at a time. (Note that this is actually for developer UX purposes, so that you can expect the effects of the previous method to complete before the next method runs).
